# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "street_manager_street_works_analysis"
version: "1.0.0"

# This setting configures which "profile" dbt uses for this project.
profile: "motherduck_profile"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data_tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.

vars:
  year: "{{ (run_started_at - modules.datetime.timedelta(days=32)).strftime('%Y') }}"
  month: "{{ (run_started_at - modules.datetime.timedelta(days=32)).strftime('%m') }}"

models:
  street_manager_street_works_analysis:
    impact_score_archive:
      impact_scores_england_archive:
      impact_scores_london_archive:
    uprn_usrn_counts:
      uprn_usrn_count:
    dft_data:
      dft_data_joins:
    england_overview:
      completed_list_england:
      in_progress_list_england:
      impact_scores_england:
      usrn_permit_details_england:
    london_overview:
      completed_list_london:
      in_progress_list_london:
      impact_scores_london:
      usrn_permit_details_london:
    collab_overview:
      collab_overview_england:
    emergency_works:
      emergency_works_overview_england:
