Table OS_Open_USRNs {
    usrn int [primary key]
    street_type varchar
    geometry geometry
}

Table Street_Manager_Permit_Data{
    version integer
    event_reference varchar
    event_type varchar
    event_time timestamp
    object_type varchar
    object_reference varchar
    work_reference_number varchar
    work_category varchar
    work_category_ref varchar
    work_status varchar
    work_status_ref varchar
    activity_type varchar
    permit_reference_number varchar
    permit_status varchar
    permit_conditions text
    collaborative_working boolean
    collaboration_type varchar
    collaboration_type_ref varchar
    promoter_swa_code varchar [primary key]
    promoter_organisation varchar
    highway_authority varchar
    highway_authority_swa_code varchar [primary key]
    works_location_coordinates geography
    works_location_type varchar
    town varchar
    street_name varchar
    usrn varchar [primary key]
    road_category varchar
    area_name varchar
    traffic_management_type varchar
    traffic_management_type_ref varchar
    current_traffic_management_type varchar
    current_traffic_management_type_ref varchar
    current_traffic_management_update_date timestamp
    proposed_start_date date
    proposed_start_time time
    proposed_end_date date
    proposed_end_time time
    actual_start_date_time timestamp
    actual_end_date_time timestamp
    is_ttro_required boolean
    is_covid_19_response boolean
    is_traffic_sensitive boolean
    is_deemed boolean
    close_footway varchar
    close_footway_ref varchar
}

Table GeoPlace_SWA_Code_List {
    swa_code varchar [primary key]
    account_name varchar [primary key]
    prefix varchar
    account_type varchar
    registered_for_street_manager varchar
    account_status varchar
    companies_house_number varchar
    previous_company_names varchar
    linked_parent_company varchar
    website varchar
    plant_enquiries varchar
    ofgem_electricity_licence varchar
    ofgem_gas_licence varchar
    ofcom_licence varchar
    ofwat_licence varchar
    company_subsumed_by varchar
    swa_code_of_new_company varchar
    date_time_processed varchar
    region varchar
    authority_type varchar
}

Table DfT_LAs_API {
    id integer
    name varchar [primary key]
    region_id integer
    ita_id integer
    ons_code varchar
    authority_type varchar
}

Table DfT_Road_Lengths {
    ons_area_code varchar [primary key]
    region varchar
    local_authority varchar
    trunk_motorways_km decimal
    principal_motorways_km decimal
    all_motorways_km decimal
    trunk_rural_a_roads_km decimal
    trunk_urban_a_roads_km decimal
    principal_rural_a_roads_km decimal
    principal_urban_a_roads_km decimal
    all_a_roads_km decimal
    major_trunk_roads_km decimal
    major_principal_roads_km decimal
    all_major_roads_km decimal
    rural_b_roads_km decimal
    urban_b_roads_km decimal
    rural_c_and_u_roads_km decimal
    urban_c_and_u_roads_km decimal
    minor_roads_km decimal
    total_road_length_km decimal
    year integer
    notes varchar
}

Table DfT_Traffic_Flows {
    local_authority_or_region_code varchar [primary key]  // Local Authority or Region Code
    region varchar
    ita varchar  // Integrated Transport Authority
    local_authority varchar
    year integer
    traffic_flow decimal
    notes varchar
    units varchar

}

// Creating indexes for common queries

Ref: Street_Manager_Permit_Data.usrn > OS_Open_USRNs.usrn
Ref: Street_Manager_Permit_Data.highway_authority_swa_code > GeoPlace_SWA_Code_List.swa_code
Ref: Street_Manager_Permit_Data.promoter_swa_code > GeoPlace_SWA_Code_List.swa_code
Ref: DfT_LAs_API.name > GeoPlace_SWA_Code_List.account_name
Ref: DfT_Road_Lengths.ons_area_code > DfT_LAs_API.ons_code
Ref: DfT_Traffic_Flows.local_authority_or_region_code > DfT_LAs_API.ons_code
