{% set table_alias = 'completed_works_list_' ~ var('year') ~ '_' ~ var('month') %}
{{ config(materialized='table', alias=table_alias) }}

{% set current_schema = 'raw_data_' ~ var('year') %}
{% set current_table = '"' ~ var('month') ~ '_' ~ var('year') ~ '"' %}

SELECT 
    w.event_type,
    w.event_time,
    w.permit_reference_number,
    w.promoter_organisation,
    w.promoter_swa_code,
    w.highway_authority,
    w.highway_authority_swa_code,
    w.work_category,
    w.proposed_start_date,
    w.proposed_end_date,
    w.actual_start_date_time,
    w.actual_end_date_time,
    w.collaborative_working,
    w.activity_type,
    w.is_traffic_sensitive,
    w.is_ttro_required,
    w.street_name,
    w.usrn,
    w.road_category,
    w.work_status_ref,
    u.geometry
FROM {{ current_schema }}.{{ current_table }} w
LEFT JOIN os_open_usrns.open_usrns_latest u ON w.usrn = u.usrn
WHERE w.work_status_ref = 'completed'
    AND w.highway_authority IN (
        'LONDON BOROUGH OF BARNET',
        'TRANSPORT FOR LONDON (TFL)',
        'LONDON BOROUGH OF HARROW',
        'LONDON BOROUGH OF BRENT',
        'LONDON BOROUGH OF TOWER HAMLETS',
        'LONDON BOROUGH OF ENFIELD',
        'LONDON BOROUGH OF EALING',
        'LONDON BOROUGH OF MERTON',
        'LONDON BOROUGH OF CROYDON',
        'LONDON BOROUGH OF BARKING AND DAGENHAM',
        'LONDON BOROUGH OF SUTTON',
        'LONDON BOROUGH OF BEXLEY',
        'ROYAL BOROUGH OF KENSINGTON AND CHELSEA',
        'LONDON BOROUGH OF SOUTHWARK',
        'LONDON BOROUGH OF HILLINGDON',
        'LONDON BOROUGH OF CAMDEN',
        'LONDON BOROUGH OF WALTHAM FOREST',
        'LONDON BOROUGH OF REDBRIDGE',
        'CITY OF WESTMINSTER',
        'ROYAL BOROUGH OF GREENWICH',
        'LONDON BOROUGH OF ISLINGTON',
        'LONDON BOROUGH OF HARINGEY',
        'LONDON BOROUGH OF NEWHAM',
        'LONDON BOROUGH OF HACKNEY',
        'LONDON BOROUGH OF HAMMERSMITH & FULHAM',
        'LONDON BOROUGH OF HOUNSLOW',
        'LONDON BOROUGH OF WANDSWORTH',
        'ROYAL BOROUGH OF KINGSTON UPON THAMES',
        'LONDON BOROUGH OF LAMBETH',
        'LONDON BOROUGH OF HAVERING',
        'LONDON BOROUGH OF RICHMOND UPON THAMES',
        'LONDON BOROUGH OF LEWISHAM',
        'CITY OF LONDON CORPORATION',
        'LONDON BOROUGH OF BROMLEY'
    )
GROUP BY
    w.event_type,
    w.event_time,
    w.permit_reference_number,
    w.promoter_organisation,
    w.promoter_swa_code,
    w.highway_authority,
    w.highway_authority_swa_code,
    w.work_category,
    w.proposed_start_date,
    w.proposed_end_date,
    w.actual_start_date_time,
    w.actual_end_date_time,
    w.collaborative_working,
    w.activity_type,
    w.is_traffic_sensitive,
    w.is_ttro_required,
    w.street_name,
    w.usrn,
    w.road_category,
    w.work_status_ref,
    u.geometry
