version: 2

sources:
  - name: street_manager
    schema: street_manager
    tables:
      - name: completed_works_list_england_latest
      - name: in_progress_works_list_england_latest
      - name: uprn_usrn_counts_latest
      - name: dft_la_data_latest
