name: Pytest Street Manager Tests

on:
  workflow_run:
    workflows: ["Ruff Linter Check & Env File Safeguard"]
    types:
      - completed

jobs:
  pytest:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      - name: Run pytest
        run: pytest tests/street_manager_tests
